version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculator-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: calculator-redis
    ports:
      - "6379:6379"
